### ISSUE TITLE
Release 1.0?

### ISSUE THREAD

**Issue by dpc** [zonyitoo/context-rs#28]
Hi,

Any idea when 1.0 will be released?

**Comment by lhecker** [comment]
I'm currently busy with my exams, but IMO I'd be possible to release it within this week if no other issues pop up.

**Comment by lhecker** [comment]
I think it's appropriate to say that you can start experimenting with the 1.0 branch already if you'd like to, because I'm 90% sure that the only thing that might change is a unit-test due to #27, or some documentation.

**Comment by dpc** [comment]
miioco master branch have been already ported to contex-rs#1.0 and it works fine in Linux&Windows. As we want to release on crates.io soon, we're blocked on context-rs.

**Comment by zonyitoo** [comment]
@dpc Wow, so quick! As @lhecker said, we can release 1.0 anytime if no other issues pop up. We have found some fatal issues before in this branch, so I suggest that we could release this branch in the weekend and make sure that everything is work.

From now on, lets hope there are no other users open issues. :)

**Comment by dpc** [comment]
Have you considered one more 0.x release? In rather small community like Rust, I have noticed that the ode gets reall testing only after a release on crates.io.

**Comment by dpc** [comment]
You could release 0.x now, and 1.0 in a month, if nothing pops up.

**Comment by zonyitoo** [comment]
@dpc I haven't made any useful modifications in 0.x . And I think I have already published some versions of 0.x on the crates.io.

**Comment by dpc** [comment]
I mean: take 1.0 branch and release it as 0.8 or whatever is the latest. After it receives some downloads and testing, release 1.0.

**Comment by zonyitoo** [comment]
@dpc Sounds fair. @lhecker Do you think it is a good idea?

**Comment by dpc** [comment]
Also, I think it's possible to release things like `1.0rc1` or `1.0alpha` etc.

**Comment by lhecker** [comment]
Well the code base of this is quite small and received extensive testing on 11 different platforms using test-cases, which are much larger in total than the actual code itself. So the probability of errors in the code is IMO _very_ small.

I'd still be nice if someone would test this on a Android phone though, so… I guess we could release a `1.0rc1` version, although I'd personally prefer to release a `1.0.0` instead, because we could release a `1.0.1` etc. later on anyways if issues come up.

**Comment by zonyitoo** [comment]
Ok, let me switch the 1.0 branch as the master branch.

@lhecker Should I rebase the commits? I think it looks Ok though.

**Comment by lhecker** [comment]
No! We still need to fix the stack alignment unit test for ARM… I'll fix that today in the coming hours and after that we could actually merge and release the code.

> Should I rebase the commits?

Do you mean you want to smash the commits into one? Because that would be impossible. Otherwise I'd simply merge the branches (with or without a PR) and push it to master.

We need to set up the documentation page beforehand - could you do this today, @zonyitoo?

**Comment by zonyitoo** [comment]
@lhecker I think the https://crates.fyi will do the trick. 

https://crates.fyi/crates/context/0.2.1/ This is the document.

And I will leave the job about merging to you, you could merge it right after you have done your modifications. :)
And then I will publish it to crates.io immediately.

**Comment by lhecker** [comment]
Cool! I think I'll push only 3 more commits:
- A fix for the stack alignment unit test
- Pull the newest assembler code from Boost.Context
- Add the link to the README.md

And then we should be good to go.

**Comment by lhecker** [comment]
Hey @dpc! 1.0 should be out until tomorrow (if nothing goes wrong). :blush:

**Comment by dpc** [comment]
Wow. You guys are really fast responding. Awesome. I will release mioco this/next week.

**Comment by lhecker** [comment]
@dpc Thanks for your compliments. And @zonyitoo released 1.0.0 just now. :blush:

**Comment by dpc** [comment]
Congratulations to all people involved!
